version: '3.9'
services:
  service:
    build: .
    env_file: .env
    container_name: api
    volumes:
      - './src:/opt/bank/src'
    ports:
      - '3001:3001'
    environment:
      - NODE_ENV=development
    depends_on:
      - postgres

  postgres:
    image: postgres:13.2
    volumes:
      - './bbdd:/var/lib/postgresql/data'
    ports:
      - 5432
    environment:
      - POSTGRES_PASSWORD=password
